### ISSUE TITLE
Unable to build project - The "GenerateReferences" task failed unexpectedly.

### ISSUE THREAD

**Issue by NoLevelCap** [NuclearPowered/Reactor#13]
I've setup my workspace as set out by https://docs.reactor.gg/docs and I get this issue when trying to build. I'm not sure what I could be doing differently, I've tried deleting and regetting AmongUs, I've also updated to a new oxygenfilter version on nuget. 

The "GenerateReferences" task failed unexpectedly.
System.NullReferenceException: Type GOBEMNFEJPH (name: EnterCodeMinigame) was not found!
   at Reactor.OxygenFilter.ObfuscationMapper.<>c__DisplayClass8_0.<Map>g__MapType|1(MappedType type, TypeDefinition typeDef)
   at Reactor.OxygenFilter.ObfuscationMapper.Map()
   at Reactor.OxygenFilter.OxygenFilter.Start(String mappings, FileInfo dumpedDll, FileInfo outputDll)
   at Reactor.OxygenFilter.MSBuild.GenerateReferences.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	ExtraRoles	C:\Users\USER\\.nuget\packages\reactor.oxygenfilter.msbuild\0.2.3\build\Reactor.OxygenFilter.MSBuild.props	27

**Comment by DaemonBeast** [comment]
@NoLevelCap This seems to be a common problem for many people.

In the `.csproj`, have you updated the mappings to `0.2.0`, updated the Among Us version to `2021.3.5` and updated OxygenFilter to `0.2.9`?

**Comment by ahmed-dardery** [comment]
> @NoLevelCap This seems to be a common problem for many people.
> 
> In the `.csproj`, have you updated the mappings to `0.2.0`, updated the Among Us version to `2021.3.5` and updated OxygenFilter to `0.2.9`?

and ran a build using `dotnet build`?

**Comment by NoLevelCap** [comment]
Thank you @DaemonBeast & @ahmed-dardery - The mappings and Among Us versions were set incorrectly.
