### ISSUE TITLE
Deobfuscation error

### ISSUE THREAD

**Issue by youtissoum** [NuclearPowered/Reactor#16]
i just followed the docs and when i launch it it gives me this error :
`Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "Deobfuscate" task failed unexpectedly.
Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   at Mono.Cecil.TypeReference.Resolve()
   at Reactor.OxygenFilter.MSBuild.Deobfuscate.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	tuto	C:\Users\NATAEL\.nuget\packages\reactor.oxygenfilter.msbuild\0.2.9\build\Reactor.OxygenFilter.MSBuild.props	51	
`

**Comment by Netika503** [comment]
no. stop

**Comment by youtissoum** [comment]
i just want to make an among us mod

**Comment by DaemonBeast** [comment]
I bet you're using Visual Studio. Visual Studio doesn't like working with Reactor.

what you can try is running `dotnet build` in a command prompt in the mod solution's directory.

**Comment by youtissoum** [comment]
oh, it worked but do you have a free text editor that works with reactor

**Comment by DaemonBeast** [comment]
@youtissoum Visual Studio should compile fine now, so you should stick with it.

The only other "good" (in my opinion, better) C# IDE is Jetbrains Rider, but that costs a lot (unless you can qualify for one of the student or open-source licenses that let you use it for a couple of years for free).

**Comment by youtissoum** [comment]
it works now
